==============================================================
#1 type

EXPLAIN PLAN FOR
SELECT --+ PARALLEL(a, 10)
  FIRST_NAME,
  LAST_NAME,
  AGE_CATEGORY,
  COUNTRY,
  SUM(TOT_SALE_SUM) AS TOT_SALE_SUM
FROM BL_DM.DIM_CUSTOMERS_SCD a, BL_DM.FCT_RETAIL_SALES_DD b
WHERE a.CUSTOMER_SURR_ID = b.CUSTOMER_SURR_ID
GROUP BY FIRST_NAME,
         LAST_NAME,
         AGE_CATEGORY,
         COUNTRY;
         
SELECT * FROM TABLE (dbms_xplan.display);

EXPLAIN PLAN FOR
SELECT --+ PARALLEL(a, 10)
  AGE_CATEGORY,
  REGION,
  SUM(TOT_SALE_AMOUNT) AS TOT_SALE_AMOUNT
FROM BL_DM.DIM_CUSTOMERS_SCD a, BL_DM.FCT_RETAIL_SALES_DD b
WHERE a.CUSTOMER_SURR_ID = b.CUSTOMER_SURR_ID
GROUP BY AGE_CATEGORY,
         REGION;
         
SELECT * FROM TABLE (dbms_xplan.display);

==============================================================
#2 type

ALTER TABLE SALES_BY_CUSTOMERS PARALLEL 8;

EXPLAIN PLAN FOR
SELECT AGE_CATEGORY,
       COUNTRY,
       SUM(RECEIPTS_SUM)
FROM   SALES_BY_CUSTOMERS
GROUP BY AGE_CATEGORY,
         COUNTRY;
         
SELECT * FROM TABLE (dbms_xplan.display);