-- Create a new tablespace. 

CREATE TABLESPACE tbs_pdb_dwh DATAFILE
    'TBS_PDB_DWH.DBF' SIZE 104857600
        AUTOEXTEND ON NEXT 20971520
NOLOGGING SEGMENT SPACE MANAGEMENT AUTO EXTENT MANAGEMENT LOCAL AUTOALLOCATE;