BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_1ST', OBJECT_NAME => 'CLS_STORES', USER_NAME => 'BL_DM');
END;

BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_1ST', OBJECT_NAME => 'CLS_EMPLOYEES', USER_NAME => 'BL_DM');
END;

BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_1ST', OBJECT_NAME => 'CLS_CUSTOMERS', USER_NAME => 'BL_DM');
END;

BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_1ST', OBJECT_NAME => 'CLS_PRODUCTS', USER_NAME => 'BL_DM');
END;