  CREATE TABLE REGIONS
   (	"REGION_ID" NUMBER, 
	"REGION_NAME" VARCHAR2(25 BYTE)
   );
  
Insert into Valeryia_Lupanava.REGIONS (REGION_ID,REGION_NAME) values (1,'Europe');
Insert into Valeryia_Lupanava.REGIONS (REGION_ID,REGION_NAME) values (2,'Americas');
Insert into Valeryia_Lupanava.REGIONS (REGION_ID,REGION_NAME) values (3,'Asia');
Insert into Valeryia_Lupanava.REGIONS (REGION_ID,REGION_NAME) values (4,'Middle East and Africa');

  CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID);
  
ALTER TABLE REGIONS ADD CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID);
  ALTER TABLE REGIONS MODIFY (REGION_ID CONSTRAINT REGION_ID_NN NOT NULL ENABLE);