SELECT 
 DECODE(GROUPING_ID((TO_CHAR(TIME_ID,'YYYY-MM'))), '1', 'GRAND TOTAL', TO_CHAR(TIME_ID,'YYYY-MM')) as YEAR_MONTH,
(CASE WHEN (DECODE(GROUPING_ID((TO_CHAR(TIME_ID,'YYYY-MM')),CH.CHANNEL_DESC), '1', 'Total by Channels', CH.CHANNEL_DESC))IS NULL 
 THEN ' ' 
 ELSE (DECODE(GROUPING_ID((TO_CHAR(TIME_ID,'YYYY-MM')),CH.CHANNEL_DESC), '1', 'Total by Channels', CH.CHANNEL_DESC)) END) as CHANNEL,
(CASE WHEN (DECODE(GROUPING_ID((TO_CHAR(TIME_ID,'YYYY-MM')),CH.CHANNEL_DESC, CN.COUNTRY_NAME), '1', 
                   (CASE WHEN CH.CHANNEL_DESC LIKE 'Internet' 
                    THEN 'Internet Sales Total by States' 
                    ELSE 'Direct Sales Total by States' END),CN.COUNTRY_NAME)) IS NULL 
 THEN ' ' 
 ELSE (DECODE(GROUPING_ID((TO_CHAR(TIME_ID,'YYYY-MM')),CH.CHANNEL_DESC, CN.COUNTRY_NAME), '1', 
             (CASE WHEN CH.CHANNEL_DESC LIKE 'Internet' 
              THEN 'Internet Sales Total by States' 
              ELSE 'Direct Sales Total by States' END),CN.COUNTRY_NAME)) END) as COUNTRY,
(CASE WHEN MAX(AMOUNT_SOLD) > 1000 
      THEN (SUBSTR(ROUND(MAX(AMOUNT_SOLD)),1,2) || ',' || 
              (CASE WHEN MAX(AMOUNT_SOLD) > 1000 
               THEN SUBSTR(ROUND(MAX(AMOUNT_SOLD)),-3,3) 
               ELSE SUBSTR(ROUND(MAX(AMOUNT_SOLD)),-2,3) END)) 
      ELSE TO_CHAR(ROUND(MAX(AMOUNT_SOLD))) END) as MAX_SALES$, 
(CASE WHEN MIN(AMOUNT_SOLD) > 1000 
      THEN (SUBSTR(ROUND(MIN(AMOUNT_SOLD)),1,2) || ',' || 
              (CASE WHEN MIN(AMOUNT_SOLD) > 1000 
               THEN SUBSTR(ROUND(MIN(AMOUNT_SOLD)),-3,3) 
               ELSE SUBSTR(ROUND(MIN(AMOUNT_SOLD)),-2,3) END)) 
      ELSE TO_CHAR(ROUND(MIN(AMOUNT_SOLD))) END) as MAX_SALES$, 
(CASE WHEN SUM(AMOUNT_SOLD) > 9999 
      THEN (SUBSTR(ROUND(SUM(AMOUNT_SOLD)),1,2) || ',' || 
              (CASE WHEN SUM(AMOUNT_SOLD) > 1000 
               THEN SUBSTR(ROUND(SUM(AMOUNT_SOLD)),-3,3) 
               ELSE 
               SUBSTR(ROUND(SUM(AMOUNT_SOLD)),-2,3) 
               END)) 
      ELSE (SUBSTR(ROUND(SUM(AMOUNT_SOLD)),1,1) || ',' || SUBSTR(ROUND(SUM(AMOUNT_SOLD)),-3,4))
      END) as SALES$ 
FROM  SALES SL LEFT JOIN CUSTOMERS CS ON SL.CUST_ID = CS.CUST_ID
               LEFT JOIN CHANNELS CH ON SL.CHANNEL_ID = CH.CHANNEL_ID
               LEFT JOIN COUNTRIES CN ON CS.COUNTRY_ID = CN.COUNTRY_ID
WHERE TO_CHAR(TIME_ID,'YYYY-MM') = '2000-12'
  AND CH.CHANNEL_DESC IN ('Internet', 'Direct Sales')
GROUP BY ROLLUP(
      TO_CHAR(TIME_ID,'YYYY-MM'),
      CH.CHANNEL_DESC, 
      CN.COUNTRY_NAME);