-- Creating table with partitions.
CREATE TABLE PT_EMPLOYEES_LIST
( EMPLOYEE_ID	NUMBER(6,0),
  JOB_ID	    VARCHAR2(10 BYTE),
  HIRE_DATE	  DATE
 )
 PARTITION BY LIST(JOB_ID)
 (partition PT_1 VALUES ('AD_VP','FI_ACCOUNT' ),
  partition PT_2 VALUES ('ST_CLERK','ST_MAN' ),
  partition PT_3 VALUES ('SA_REP' )
 );
 
-- Filling table with data.
INSERT INTO PT_EMPLOYEES_LIST(EMPLOYEE_ID, JOB_ID, HIRE_DATE)
SELECT      EMPLOYEE_ID, JOB_ID, HIRE_DATE
FROM        EMPLOYEES
WHERE JOB_ID IN ('AD_VP', 'FI_ACCOUNT', 'ST_CLERK', 'ST_MAN', 'SA_REP');

-- Selecting all data from the table.
SELECT *
FROM PT_EMPLOYEES_LIST;

SELECT COUNT(*) 
FROM PT_EMPLOYEES_LIST;

-- Selecting 1-st partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_LIST PARTITION(PT_1);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_LIST PARTITION(PT_1);

-- Selecting 2-nd partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_LIST PARTITION(PT_2);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_LIST PARTITION(PT_2);

-- Selecting 3-rd partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_LIST PARTITION(PT_3);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_LIST PARTITION(PT_3);