-- Creating table with partitions.
CREATE TABLE PT_EMPLOYEES_HASH
( EMPLOYEE_ID	NUMBER(6,0),
  JOB_ID	    VARCHAR2(10 BYTE),
  HIRE_DATE	  DATE
 )
 PARTITION BY HASH(HIRE_DATE)
 (partition PT_1,
  partition PT_2,
  partition PT_3
 );
 
-- Filling table with data.
INSERT INTO PT_EMPLOYEES_HASH(EMPLOYEE_ID, JOB_ID, HIRE_DATE)
SELECT      EMPLOYEE_ID, JOB_ID, HIRE_DATE
FROM        EMPLOYEES;

-- Selecting all data from the table.
SELECT *
FROM PT_EMPLOYEES_HASH;

SELECT COUNT(*) 
FROM PT_EMPLOYEES_HASH;

-- Selecting 1-st partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_HASH PARTITION(PT_1);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_HASH PARTITION(PT_1);

-- Selecting 2-nd partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_HASH PARTITION(PT_2);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_HASH PARTITION(PT_2);

-- Selecting 3-rd partition data from the table.
SELECT * 
FROM PT_EMPLOYEES_HASH PARTITION(PT_3);

SELECT COUNT(*) 
FROM PT_EMPLOYEES_HASH PARTITION(PT_3);