BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_LAB', OBJECT_NAME => 'CLS_COUNTRIES', USER_NAME => 'BL_3NF_LAB');
END;

BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_LAB', OBJECT_NAME => 'CLS_REGIONS', USER_NAME => 'BL_3NF_LAB');
END;

BEGIN
  pkg_grants.USER_GRANT(GRANT_NAME => 'SELECT', SCHEMA_NAME => 'BL_CL_LAB', OBJECT_NAME => 'CLS_CONTINENTS', USER_NAME => 'BL_3NF_LAB');
END;
