EXEC SYS.DBMS_TTS.TRANSPORT_SET_CHECK(ts_list => 'TEST_DATA_TT', incl_constraints => TRUE);

SELECT * FROM SYS.TRANSPORT_SET_VIOLATIONS;

ALTER TABLESPACE test_data_tt READ ONLY;

ALTER TABLESPACE tbs_pdb_lab READ ONLY;

GRANT READ, WRITE ON DIRECTORY temp_dir TO system;

