CREATE TABLESPACE test_data
  DATAFILE 'test_data.dbf'
  SIZE 1M AUTOEXTEND ON NEXT 1M;

CREATE USER test_user IDENTIFIED BY test_user 
DEFAULT TABLESPACE test_data TEMPORARY TABLESPACE temp 
QUOTA UNLIMITED ON test_data;

GRANT CONNECT TO test_user;
GRANT RESOURCE TO test_user;
GRANT CREATE PUBLIC DATABASE LINK TO test_user;

SELECT owner,db_link FROM dba_db_links;


